<a href="https://colab.research.google.com/github/fatimahaidara/Computer_Vision/blob/main/convnet_tutorial1b_Fatoumata_HAIDARA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch import Tensor

# Tutorial 1b: Softmax Function

**Question:** To have the logistic regressor output probabilities, they need to be processed through a softmax layer. Implement a softmax layer yourself. What numerical issues may arise in this layer? How can you solve them? Use the testing code to confirm you implemented it correctly.

In [ ]:
logits = torch.rand((1, 20)) + 100
logits

tensor([[100.2057, 100.6179, 100.5677, 100.9142, 100.6477, 100.8188, 100.0756,
         100.5973, 100.6206, 100.8988, 100.8950, 100.6308, 100.6846, 100.8180,
         100.0772, 100.0258, 100.8565, 100.6856, 100.2978, 100.4755]])

In [ ]:
def bad_softmax(x: Tensor) -> Tensor:
    return torch.exp(x) / torch.sum(torch.exp(logits), axis=1)

In [ ]:
bad_softmax(logits)

tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [ ]:
torch.sum(bad_softmax(logits))

tensor(nan)

##Solve the overflow problem,we can apply the 

In [ ]:
def good_softmax(x: Tensor) -> Tensor:
    ###########################################################################
    # TODO: Implement a more stable way to compute softmax                    #
    ###########################################################################

    return torch.exp(x- torch.max(x)) / torch.sum(torch.exp((logits - torch.max(x))), axis=1)

In [ ]:
good_softmax(logits)

tensor([[0.0335, 0.0505, 0.0481, 0.0680, 0.0521, 0.0618, 0.0294, 0.0495, 0.0507,
         0.0669, 0.0667, 0.0512, 0.0540, 0.0617, 0.0294, 0.0280, 0.0641, 0.0541,
         0.0367, 0.0438]])

In [ ]:
torch.sum(good_softmax(logits))

tensor(1.)

Because of numerical issues like the one you just experiences, PyTorch code typically uses a `LogSoftmax` layer.

In [ ]:
def good_softmax(x: Tensor) -> Tensor:
    ###########################################################################
    # TODO: Implement a more stable way to compute softmax                    #
    ###########################################################################
    # log_soft = torch.nn.LogSoftmax(dim=1)
    # log_out = log_soft(logits)
    
    return torch.log( torch.exp(x) / torch.sum(torch.exp(logits), axis=1))

In [ ]:
good_softmax(logits)

tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

**Question [optional]:** PyTorch automatically computes the backpropagation gradient of a module for you. However, it can be instructive to derive and implement your own backward function. Try and implement the backward function for your softmax module and confirm that it is correct.

In [ ]:
import numpy as np 